[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = "/migrations/"

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["project", "accounts", "ideas"]

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["migrations"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "ANN", "C4", "SIM"]
ignore = ["ANN204", "ANN002", "ANN003"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "project.settings.dev"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "-ra"

